// This file is automatically generated from Google's Material Icons.
/**
 * Fetches the full list of Material Icon names from Google Fonts.
 * Returns an array of strings like ["3d_rotation","access_alarm",…]
 */
export async function fetchAllIcons() {
  const res = await fetch("https://fonts.google.com/metadata/icons");
  let txt = await res.text();
  // strip the weird prefix )]}'\n
  txt = txt.replace(/^\)\]\}'\s*/, "");
  const json = JSON.parse(txt);
  return json.icons.map(icon => icon.name);
}

// Fallback static array for immediate use (e.g. the "+" button and bookmark icons)
export const icons = [
  'add',
  'bookmark',
  'star',
  // …add any other icons your components expect synchronously…
];